project:
  type: website
  output-dir: docs

website:
  title: "Nick Lewis"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: Portfolio
      - href: blog.qmd
        text: Blog

    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: linkedin
        href: https://linkedin.com/in/yourusername

  page-footer:
    center: "2026 Nick Lewis"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    page-layout: full