project:
  type: website
  output-dir: docs

website:
  title: "Nick Lewis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: About Me
      - href: portfolio.qmd
        text: GIS Projects
    right:
      - icon: github
        href: https://github.com/ntlewis1251
      - icon: linkedin
        href: https://www.linkedin.com/in/nick-lewis-geo/

format:
  html:
    theme: cosmo
    css: styles.css