---
title: "Resume"
---

## EDUCATION
**Bachelor of Arts and Sciences in Geology, Minor in Data Science** at [William & Mary](https://www.wm.edu/as/geology/)
W&M Stofan Scholarship, William & Mary Geology and Elle Stofan

## TECHNICAL EXPERIENCE

### Geotechnical Engineering Intern
**GET Solutions, Inc., a Terracon Company** | June - August 2024

* Performed soil testing using multiple techniques, including sample collection by hand auger and from drilling operations.
* Operational, field-level groundwater and environmental testing.
* Selected for an intern conference in Charlotte, NC.
* Experienced office work and computational work related to geotechnical engineering.
* **References:** Dave Ferko ((757) 620-1400), GEotechnical Department Manager; Greg Lewis ((202) 669-5755), Project Manager.

### Honors Thesis Author
**William & Mary** | "Potential causes of clustered knickpoints in the Appalachian Mountains"

* Scientific writing and figure making for the Geology department.
* Working with large datasets and manipulating large $(>200k~km^{2})$ rasters.
* Experience writing proposals, presenting results, and organizing large coding projects.

### Creator | Stream Analysis for Geoscientists
**PyCogs** 

* Educational resource for geoscientists using Python for stream analysis.
* Experience creating Jupyter Notebooks and communicating complex information.

### Panelist | Bringing Coding to the Geoscience Classroom
**National Association of Geoscience Teachers** 

* Assisted geoscience teachers in computational education.

## SKILLS

| Category | Details |
| :--- | :--- |
| **Software/Languages** | Python, ARCGIS, QGIS, gINT, C, Objective C, VSCode, Jupyter Notebooks |
| **Physical Tools** | Proctor, CBR, Liquid Limit (Casagrande), Concrete compression, Soil core analysis, Well depth, Percolation, VOC testing, Petrographic microscope |
| **Python Proficiencies** | Matplotlib, Seaborn, Pandas, GeoPandas, NumPy, Math, SciKitLearn |
| **Communication** | Scientific writing, funding proposals, stratigraphic column/core log creation (ASTM/VDOT) |

## ACTIVITIES
* **WCWM 90.9 FM** (2022-2026)
* **G.R.A.V.E.L. Lab** (2024-2026)
* **History Club** (2022-2026)
* **SKIFFY** (2022-2026)
* **Tabletop Club** (2022-2026)