project:
  type: website
  output-dir: quarto

website:
  title: "Nick Lewis"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: GIS Portfolio

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true